PS1='\[\e[38;5;44m\]\u@\h\[\e[0m\]:\[\e[38;5;40m\]\w\[\e[0m\]\$ '
if [ "$EUID" -eq 0 ]; then
    PS1='\[\e[38;5;196m\]\u@\h\[\e[0m\]:\[\e[38;5;40m\]\w\[\e[0m\]# '
fi
alias ls='ls --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dexec='docker exec -it'
alias dlogs='docker logs -f'
alias dprune='docker system prune -af'
alias dc='docker compose'
if command -v kubectl >/dev/null 2>&1; then
    alias k='kubectl'
    alias kg='kubectl get'
    alias kd='kubectl describe'
    alias kdel='kubectl delete'
    alias kl='kubectl logs -f'
    alias kx='kubectl exec -it'
fi
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph'
alias ..='cd ..'
alias ...='cd ../..'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias ip='ip --color=auto'
