#!/usr/bin/env bash
# Composes the local file:// Veilbox development DNF repository from
# built RPMs and configures it on this machine.
#
# This is the development equivalent of the future hosted Veilbox
# repository: veil installs experiences by package name through DNF,
# resolved from this repository. No local file paths are special-cased
# by Veilbox code.
set -euo pipefail

cd "$(dirname "$0")/.."

REPO_DIR="${VEILBOX_REPO_DIR:-/srv/veilbox-repo}"
REPO_ID="veilbox-dev"
REPO_FILE="/etc/yum.repos.d/${REPO_ID}.repo"

if [[ ! -d packages/build/RPMS ]]; then
    echo "error: no built RPMs in packages/build/RPMS — run scripts/build-rpms.sh first" >&2
    exit 1
fi

sudo mkdir -p "${REPO_DIR}"
# Drop stale RPMs first: republishing is a no-op, but a leftover same-
# NEVRA RPM from an earlier compose would corrupt repo metadata.
sudo rm -f "${REPO_DIR}"/*.rpm
sudo cp packages/build/RPMS/*/*.rpm "${REPO_DIR}/"
sudo createrepo_c --update "${REPO_DIR}"

sudo tee "${REPO_FILE}" >/dev/null <<EOF
# Veilbox development repository (local file:// mirror of the future
# hosted Veilbox repository). Generated by scripts/compose-repo.sh.
[${REPO_ID}]
name=Veilbox Development Repository
baseurl=file://${REPO_DIR}
enabled=1
gpgcheck=0
EOF

echo "--- repository composed ---"
sudo createrepo_c --update "${REPO_DIR}" 2>/dev/null || true
sudo dnf repolist "${REPO_ID}"
