---
# Calamares main configuration for Veilbox
modules-search: [ /usr/lib/calamares/modules, /usr/share/calamares/modules ]
instances:
    - id:         veilbox
      module:     welcome
      config:     welcome-veilbox.conf
    - id:         veilbox
      module:     locale
      config:     locale-veilbox.conf
    - id:         veilbox
      module:     keyboard
      config:     keyboard-veilbox.conf
    - id:         veilbox
      module:     partition
      config:     partition-veilbox.conf
    - id:         veilbox
      module:     users
      config:     users-veilbox.conf
    - id:         veilbox
      module:     summary
      config:     summary-veilbox.conf
    - id:         veilbox
      module:     grubcfg
      config:     grubcfg-veilbox.conf
    - id:         veilbox
      module:     bootloader
      config:     bootloader-veilbox.conf
    - id:         veilbox
      module:     finished
      config:     finished-veilbox.conf

sequence:
    - show:
        - welcome-veilbox
        - locale-veilbox
        - keyboard-veilbox
        - partition-veilbox
        - users-veilbox
        - summary-veilbox
    - exec:
        - partition-veilbox
        - users-veilbox
        - grubcfg-veilbox
        - bootloader-veilbox
    - show:
        - finished-veilbox

branding: veilbox
prompt-install: true
dont-chroot: false
preserve-files: []
oem-setup: false
