#!/bin/sh
set -e

lb config noauto \
    --distribution trixie \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "http://deb.debian.org/debian" \
    --mirror-chroot "http://deb.debian.org/debian" \
    --mirror-binary "http://deb.debian.org/debian" \
    --mirror-chroot-security "http://security.debian.org/debian-security" \
    --mirror-binary-security "http://security.debian.org/debian-security" \
    --debian-installer false \
    --bootappend-live "boot=live components console=ttyS0,115200n8 username=veilbox locales=en_US.UTF-8 keyboard-layouts=us timezone=UTC persistence drm.debug=0x1ff loglevel=7 fbcon=nodefer" \
    --bootappend-live-failsafe "boot=live components quiet noapath noapic" \
    --linux-packages "linux-image" \
    --linux-flavours "amd64" \
    --firmware-binary true \
    --firmware-chroot true \
    --iso-application "Veilbox Linux" \
    --iso-preparer "Veilbox" \
    --iso-publisher "Veilbox" \
    --iso-volume "Veilbox v2" \
    --memtest none \
    --parent-archive-areas "main contrib non-free non-free-firmware" \
    --initsystem systemd \
    --apt-recommends false \
    --apt-indices false \
    --apt-source-archives false \
    --cache-indices true \
    --cache-packages true \
    --compression xz \
    --zsync false \
    --verbose
