package workspace

import (
	"fmt"
	"strings"
)

// Generated file names under the Veilbox-owned workspace directory.
const (
	ShellScriptName = "shell.sh"
	TmuxConfigName  = "tmux.conf"
)

// generatedHeader is the deterministic header of every generated file.
const generatedHeader = "# Generated by Veilbox — do not edit. Manage with 'veil workspace'.\n"

// ShellScriptContent renders the managed shell include. Output is
// fully Go-constructed from validated preferences: no manifest text
// ever lands in the file unescaped.
func ShellScriptContent(p Preferences) string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	if p.Editor != "" {
		fmt.Fprintf(&b, "export EDITOR=%q\n", p.Editor)
	}
	for _, k := range p.SortedEnvNames() {
		fmt.Fprintf(&b, "export %s=%q\n", k, ExpandHome(p.Environment[k]))
	}
	for _, name := range p.SortedAliasNames() {
		v := p.Aliases[name]
		fmt.Fprintf(&b, "alias %s='%s'\n", name, strings.ReplaceAll(v, "'", "'\\''"))
	}
	if p.Prompt == PromptVeilbox {
		b.WriteString("PS1='\\[\\e[32m\\]\\u@\\h\\[\\e[0m\\]:\\w\\$ '\n")
	}
	return b.String()
}

// TmuxConfigContent renders the managed tmux configuration. It is a
// small, deterministic set of sane defaults; it carries no preference
// text.
func TmuxConfigContent() string {
	return generatedHeader +
		"set -g default-terminal \"screen-256color\"\n" +
		"set -g history-limit 10000\n" +
		"setw -g mode-keys vi\n" +
		"set -g escape-time 10\n" +
		"set -g base-index 1\n" +
		"setw -g pane-base-index 1\n"
}

// ShellIncludeLine is the single sourced line placed inside the managed
// block of ~/.bashrc. The path is resolved at apply time so a custom
// XDG_CONFIG_HOME keeps working.
func ShellIncludeLine(stateDir string) string {
	return fmt.Sprintf(`[ -f "%s" ] && . "%s"`, shellScriptPath(stateDir), shellScriptPath(stateDir))
}

// TmuxIncludeLine sources the Veilbox-owned tmux config from the
// managed block of ~/.tmux.conf.
func TmuxIncludeLine(stateDir string) string {
	return fmt.Sprintf("source-file %q", tmuxConfigPath(stateDir))
}

// shellScriptPath returns the absolute path of the generated shell
// script inside the workspace directory.
func shellScriptPath(stateDir string) string {
	return stateDir + "/" + ShellScriptName
}

// tmuxConfigPath returns the absolute path of the generated tmux
// configuration.
func tmuxConfigPath(stateDir string) string {
	return stateDir + "/" + TmuxConfigName
}
