---
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
alwaysShowPartitionLabels: true
allowManualPartitioning: true
allowReplacePartition: true
drawNestedPartitions: false
efiSystemPartitionSize: 512M
enableEncryption: true
eraseDisk: true
partitionLayout:
    - name: "efi"
      type: "512M"
      fileSystem: "fat32"
    - name: "root"
      type: "100%"
      fileSystem: "ext4"
